// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { AUTH_STORAGE_KEY, guardBrowserCloseLogout, startHeartbeat } from './sessionGuard';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// We store the auth session in localStorage so every tab shares one login (a
// new tab never re-prompts) and the session survives a quick reload. To still
// log users out when they close the WHOLE browser, a heartbeat marks the browser
// as "alive"; if no tab kept it alive, guardBrowserCloseLogout() purges the
// stored session on the next load BEFORE the client reads it. Closing a single
// tab (with others open) keeps the heartbeat fresh and does NOT log out.
// See ./sessionGuard for details.
guardBrowserCloseLogout();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: AUTH_STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Keep the browser marked "alive" while any tab is open.
startHeartbeat();